// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSSID(arg1) {
  return window['go']['gui']['App']['AddSSID'](arg1);
}

export function DeleteCreds(arg1) {
  return window['go']['gui']['App']['DeleteCreds'](arg1);
}

export function FinishWizard(arg1) {
  return window['go']['gui']['App']['FinishWizard'](arg1);
}

export function GetCreds(arg1) {
  return window['go']['gui']['App']['GetCreds'](arg1);
}

export function GetState() {
  return window['go']['gui']['App']['GetState']();
}

export function ManualLogin() {
  return window['go']['gui']['App']['ManualLogin']();
}

export function ManualLogout() {
  return window['go']['gui']['App']['ManualLogout']();
}

export function RemoveSSID(arg1) {
  return window['go']['gui']['App']['RemoveSSID'](arg1);
}

export function SaveCreds(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['App']['SaveCreds'](arg1, arg2, arg3, arg4);
}

export function ScanNetworks() {
  return window['go']['gui']['App']['ScanNetworks']();
}

export function SetActiveCred(arg1) {
  return window['go']['gui']['App']['SetActiveCred'](arg1);
}

export function SetThreshold(arg1) {
  return window['go']['gui']['App']['SetThreshold'](arg1);
}

export function Startup(arg1) {
  return window['go']['gui']['App']['Startup'](arg1);
}

export function ToggleAutoLogin(arg1) {
  return window['go']['gui']['App']['ToggleAutoLogin'](arg1);
}

export function ToggleVanguard(arg1) {
  return window['go']['gui']['App']['ToggleVanguard'](arg1);
}
