// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {context} from '../models';

export function AddSSID(arg1:string):Promise<void>;

export function DeleteCreds(arg1:string):Promise<void>;

export function FinishWizard(arg1:Array<string>):Promise<void>;

export function GetCreds(arg1:string):Promise<Record<string, string>>;

export function GetState():Promise<gui.AppState>;

export function ManualLogin():Promise<string>;

export function ManualLogout():Promise<void>;

export function RemoveSSID(arg1:string):Promise<void>;

export function SaveCreds(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ScanNetworks():Promise<Array<gui.ScannedNetwork>>;

export function SetActiveCred(arg1:string):Promise<void>;

export function SetThreshold(arg1:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleAutoLogin(arg1:boolean):Promise<void>;

export function ToggleVanguard(arg1:boolean):Promise<void>;
